apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak


resources:
  - app/deployment.yaml
  - app/volume.yaml
  - app/ingress.yaml
  - db/postgres-deployment.yaml
  - db/postgres-service.yaml
  - db/postgres-volume.yaml

secretGenerator:
- name: keycloak-env
  envs:
     - .env